repository: monasca/log-api
variants:
  - tag: master-{date}-{time}
    args:
      LOG_API_BRANCH: master
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: 20170809-155207
      CONSTRAINTS_BRANCH: master
