sudo: required
services:
  - docker
language: python

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck
    - docker-ce

env:
  - IGNORE_DOCKER_VERSION=true PYTHONUNBUFFERED=true

before_install:
  - docker --version
  - docker-compose --version
  - pip install pip --upgrade
  - pip install git+https://github.com/timothyb89/dbuild.git
  - pip install google-cloud-storage

jobs:
  include:
    - stage: lint-shellcheck
      script: bash -c 'shopt -s globstar; shellcheck **/*.sh'
    - stage: metrics-pipeline
      script: python ci.py metrics
    - stage: logs-pipeline
      script: python ci.py logs False
