version: '3'
services:

  influxdb:
    image: influxdb:latest

  agent-forwarder:
    image: monasca/agent-forwarder:master
    environment:
      NON_LOCAL_TRAFFIC: "true"

  agent-collector:
    image: monasca/agent-collector:master
    environment:
      FORWARDER_URL: "http://agent-forwarder:17123"

  influxdb-init:
    image: monasca/influxdb-init:latest
    depends_on:
      - influxdb

  alarms:
    image: monasca/alarms:1.1.0

  zookeeper:
    image: zookeeper:3.3
  kafka:
    image: monasca/kafka:0.9.0.1-2.11-1.0.1
    environment:
      ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_TOPIC_CONFIG: segment.ms=900000 # 15m
      KAFKA_CREATE_TOPICS: "\
        metrics:64:1,\
        alarm-state-transitions:12:1,\
        alarm-notifications:12:1,\
        retry-notifications:3:1,\
        events:12:1,\
        60-seconds-notifications:3:1"
    depends_on:
      - zookeeper

  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: secretmysql
  mysql-init:
    image: monasca/mysql-init:1.5.1
    environment:
      MYSQL_INIT_DISABLE_REMOTE_ROOT: "false"
      MYSQL_INIT_RANDOM_PASSWORD: "false"

  keystone:
    image: monasca/keystone:1.0.7
    environment:
      KEYSTONE_HOST: keystone
      KEYSTONE_PASSWORD: secretadmin
      KEYSTONE_DATABASE_BACKEND: mysql
      KEYSTONE_MYSQL_HOST: mysql
      KEYSTONE_MYSQL_USER: keystone
      KEYSTONE_MYSQL_PASSWORD: keystone
      KEYSTONE_MYSQL_DATABASE: keystone
    volumes:
      - ./keystone/preload.yml:/preload.yml
    depends_on:
      - mysql
    ports:
      - "5000:5000"
      - "35357:35357"

  monasca-sidecar:
    image: timothyb89/monasca-sidecar:1.0.0

  monasca:
    image: monasca/api:master
    environment:
      SIDECAR_URL: http://monasca-sidecar:4888/v1/ingest
    depends_on:
      - influxdb
      - keystone
      - mysql
      - zookeeper
      - kafka
      - monasca-sidecar
    ports:
      - "8070:8070"

  monasca-persister:
    image: monasca/persister:master
    depends_on:
      - monasca
      - influxdb
      - zookeeper
      - kafka

  storm-nimbus:
    image: monasca/storm:1.0.3
    command: storm nimbus
    environment:
      STORM_LOCAL_HOSTNAME: "storm-nimbus"
      WORKER_LOGS_TO_STDOUT: "true"
    depends_on:
      - zookeeper
      - kafka

  storm-supervisor:
    image: monasca/storm:1.0.3
    command: storm supervisor
    depends_on:
      - storm-nimbus
      - zookeeper
      - kafka

  thresh-init:
    image: monasca/thresh:master
    environment:
      STORM_WAIT_RETRIES: 49
    depends_on:
      - zookeeper
      - storm-nimbus
      - storm-supervisor

  monasca-notification:
    image: monasca/notification:master
    environment:
      NF_PLUGINS: "webhook"
    depends_on:
      - monasca
      - zookeeper
      - kafka
      - mysql

  grafana:
    image: monasca/grafana:4.0.0-1.1.1
    environment:
      GF_AUTH_BASIC_ENABLED: "false"
      GF_USERS_ALLOW_SIGN_UP: "true"
      GF_USERS_ALLOW_ORG_CREATE: "true"
      GF_AUTH_KEYSTONE_ENABLED: "true"
      GF_AUTH_KEYSTONE_AUTH_URL: http://keystone:5000
      GF_AUTH_KEYSTONE_VERIFY_SSL_CERT: "false"
      GF_AUTH_KEYSTONE_DEFAULT_DOMAIN: "Default"
    ports:
      - "3000:3000"
    depends_on:
      - keystone
      - monasca

  grafana-init:
    image: monasca/grafana-init:1.1.0
    depends_on:
      - grafana
