version: '3'
services:

  log-metrics:
    image: monasca/log-metrics:${MON_LOG_METRICS_VERSION}
    depends_on:
      - kafka
      - zookeeper
      - log-transformer

  log-persister:
    image: monasca/log-persister:${MON_LOG_PERSISTER_VERSION}
    depends_on:
      - kafka
      - zookeeper
      - elasticsearch
      - log-transformer

  log-transformer:
    image: monasca/log-transformer:${MON_LOG_TRANSFORMER_VERSION}
    depends_on:
      - kafka
      - zookeeper
      - log-api

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - cluster.name=monasca
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300

  elasticsearch-init:
    image: monasca/elasticsearch-init:${MON_ELASTICSEARCH_INIT_VERSION}
    volumes:
      - ./elasticsearch-templates/logs.template:/templates/logs.json
    depends_on:
      - elasticsearch

  kafka-log-init:
    image: monasca/kafka-init:${MON_KAFKA_INIT_VERSION}
    environment:
      KAFKA_TOPIC_CONFIG: segment.ms=900000 # 15m
      KAFKA_CREATE_TOPICS: "\
        log:4:1,\
        log-transformed:4:1"
    depends_on:
      - kafka

  kibana:
    image: monasca/kibana:${MON_KIBANA_VERSION}
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_PINGTIMEOUT: 1000
    depends_on:
      - elasticsearch
      - keystone
    ports:
      - 5601:5601

  log-api:
    image: monasca/log-api:${MON_LOG_API_VERSION}
    depends_on:
      - keystone
      - zookeeper
      - kafka
      - memcached
    ports:
      - "5607:5607"

  log-agent:
    image: monasca/log-agent:${MON_LOG_AGENT_VERSION}
    environment:
      LOGSPOUT: ignore
    depends_on:
      - log-api
      - keystone
    ports:
      - "5610:5610"
  logspout:
    image: monasca/logspout:${MON_LOGSPOUT_VERSION}
    environment:
      LOGSPOUT: ignore
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
        - log-agent
