repository: monasca/log-agent
variants:
  - tag: 0.0.2
    aliases:
      - :latest
    args:
      # TODO(matrixik): change back to stable when PR is merged
      LOGSTASH_PLUGIN_BRANCH: pull/4/head
      JRUBY_VERSION: 9.1-alpine
      LOGSTASH_VERSION: 2.4-alpine

  - tag: master
    aliases:
      - :master-{date}-{time}
    args:
      LOGSTASH_PLUGIN_BRANCH: master
      JRUBY_VERSION: 9.1-alpine
      LOGSTASH_VERSION: 2.4-alpine
