repository: monasca/client
variants:
  - tag: 1.7.0
    aliases:
      - :latest
      - :1.7
      - :1
    args:
      CLIENT_BRANCH: 1.7.0
      PYTHON_VERSION: 2
      TIMESTAMP_SLUG: 20170809-155207

  - tag: 1.6.0
    aliases:
      - :1.6
    args:
      CLIENT_BRANCH: 1.6.0
      PYTHON_VERSION: 2
      TIMESTAMP_SLUG: 20170809-155207

  - tag: master
    aliases:
      - :master-{date}-{time}
    args:
      CLIENT_BRANCH: master
      PYTHON_VERSION: 2
      TIMESTAMP_SLUG: 20170809-155207

  - tag: pike
    args:
      CLIENT_BRANCH: stable/pike
      PYTHON_VERSION: 2
      TIMESTAMP_SLUG: 20170809-155207
