repository: monasca/api
variants:
  - tag: master
    aliases:
      - :master-{date}-{time}
    args:
      API_BRANCH: refs/changes/63/417163/13
      CONSTRAINTS_BRANCH: master
      TIMESTAMP_SLUG: 20170809-155207
