repository: monasca/persister
variants:
  - tag: master-{date}-{time}
    args:
      PERSISTER_BRANCH: master
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: 20170809-155207
      CONSTRAINTS_BRANCH: master
